version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b '0.0.0.0'"
    volumes:
      - ".:/rails"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://auth_service:password@db/auth_service_development
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: auth_service
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_service_development
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
